services:
  backend:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./:/home/server/
      - modules:/home/server/node_modules
    env_file:
      - .env
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
volumes:
  modules:

  
